language: java
jdk:
  - openjdk7
branches:
  only:
    - master

before_script: cd java-maven
install: /bin/true
script: "mvn clean install"
notifications:
  email:
    recipients:
      - aksw-nlp2rdf@lists.informatik.uni-leipzig.de
    on_success: change
    on_failure: change